- hosts: localhost
  gather_facts: 'true'
  vars:
    install_zsh: 'true'
    python_version: '3.12.0'
    go_version: '1.22.6'
    node_version: '20.9.0'
    install_go: 'true'
    install_node: 'false'
    install_python: 'false'
    install_ruby: 'false'
    install_nvim: 'false'

  tasks:
    - name: Store current OS as variable
      set_fact:
        os_family: "{{ ansible_os_family | lower }}"

    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
      when: os_family == 'Debian' 

    - name: Include tasks for OS
      include_role:
        name: "{{ os_family }}"

