- name: Clone goenv repository
  git:
    repo: https://github.com/syndbg/goenv.git
    dest: "{{ ansible_env.HOME }}/.goenv"
    update: yes

- name: Ensure zshrc contains GOENV_ROOT
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export GOENV_ROOT="$HOME/.goenv"'

- name: Ensure zshrc contains goenv bin in PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'export PATH="$GOENV_ROOT/bin:$PATH"'

- name: Ensure zshrc contains goenv init command
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: 'eval "$(goenv init -)"'


- name: Source zshrc to apply changes
  shell: source {{ ansible_env.HOME }}/.zshrc
  args:
    executable: /bin/zsh
  ignore_errors: yes  # Sourcing zshrc may not affect the current session, so ignore errors

- name: Install a specific Go version
  shell: |
    source {{ ansible_env.HOME }}/.zshrc
    goenv install -s {{ go_version }}
  args:
    executable: /bin/zsh

- name: Set the installed Go version as the global default
  shell: |
    source {{ ansible_env.HOME }}/.zshrc
    goenv global {{ go_version }}
  args:
    executable: /bin/zsh

