- name: Install node
  package:
    name: nodejs
    state: present

- name: Install npm
  package:
    name: npm
    state: present

# Use N to manage node versions and set system node versions
- name: Install N
  npm:
    name: n
    global: yes

- name: Set system node versions
  command: n {{ node_version }}
  args:
    creates: /usr/local/bin/node

