- name: Install dependencies with apt
  apt:
    name: "{{ item }}"
  loop:
    - ripgrep
    - fd-find
    - pkg-config
    - fonts-powerline
    - neovim
  become: true


- name: Copy the external config to the system
  copy:
    src: "{{ playbook_dir }}/.dotfiles/.config/nvim"
    dest: "~/.config"
    mode: '0755'

- name: Install Neovim plugins using Packer
  command: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

