- name: Install dependencies
  apt:
      name: "{{ item }}"
      state: present
  become: true
  loop:
     - build-essential
     - libssl-dev
     - zlib1g-dev
     - libbz2-dev
     - libreadline-dev
     - libsqlite3-dev
     - curl
     - git
     - libncursesw5-dev
     - xz-utils
     - tk-dev
     - libxml2-dev
     - libxmlsec1-dev
     - libffi-dev
     - liblzma-dev

- name: Install pyenv
  shell: |
    curl -k https://pyenv.run | bash
  args:
    creates: "{{ ansible_env.HOME }}/.pyenv"

- name: Configure pyenv in .zshrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: |
      export PATH="{{ ansible_env.HOME }}/.pyenv/bin:$PATH"
      eval "$(pyenv init --path)"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
    state: present

- name: Install Python {{ python_version }} using pyenv
  shell: |
    source ~/.zshrc && pyenv install {{ python_version }} && pyenv global {{ python_version }}
  args:
    executable: /bin/zsh
    creates: "{{ ansible_env.HOME }}/.pyenv/versions/{{ python_version }}"

- name: Install virutalenv
  shell: |
    pip install virtualenv
