- name: Install zsh
  package:
    name: zsh
    state: present

- name: Change default shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh

- name: Ensure zsh is installed and set as the default shell
  shell: chsh -s /bin/zsh {{ ansible_user_id }}
  when: ansible_env.SHELL != '/bin/zsh'
  become: true
